[package]
name = "discord-transcript"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10"
axum = "0.8"
base64 = "0.22"
hmac = "0.12"
hkdf = "0.12"
libc = "0.2"
regex = "1.12.2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serenity = { version = "0.12.5", default-features = false, features = ["default_native_tls", "client", "gateway", "model"] }
sha2 = "0.10"
songbird = { version = "0.6.0", default-features = false, features = ["driver", "gateway", "native", "serenity", "tungstenite", "receive"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread", "fs", "net", "signal"] }
tokio-postgres = "0.7.15"
tokio-util = { version = "0.7", features = ["io", "rt"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
futures-util = "0.3"
tower-http = { version = "0.6", features = ["fs"] }

[patch.crates-io]
hpke-rs-libcrux = { path = "vendor/hpke-rs-libcrux-0.6.1" }
